<a href="https://colab.research.google.com/github/ABDULHAI10/ABDULHAI10/blob/main/ABDNrl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [ ]:
my_list = [1,2,3,4,5]
my_list.append(45)
print(my_list)

[1, 2, 3, 4, 5, 45]


In [ ]:
my_list = [1,2,3,4,5,5,6,7,8,9,8,88,66,54,32,34,12,65,3,48,99,0]
my_list.sort()
print(my_list)

[0, 1, 2, 3, 3, 4, 5, 5, 6, 7, 8, 8, 9, 12, 32, 34, 48, 54, 65, 66, 88, 99]


In [ ]:
my_list = [1,2,3,4,5,5,6,7,8,9,8,88,66,54,32,34,12,65,3,48,99,0]
unique_list = (my_list)
print(unique_list)


[1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 8, 88, 66, 54, 32, 34, 12, 65, 3, 48, 99, 0]


In [ ]:
my_dict = {'Name':'Abdul Hai' , 'age':25 , 'Company':'NRL'}
print(my_dict)

{'Name': 'Abdul Hai', 'age': 25, 'Company': 'NRL'}


In [ ]:
del my_dict ['Company']
print(my_dict)

{'Name': 'Abdul Hai', 'age': 25}


In [ ]:
print(my_dict.keys())

dict_keys(['Name', 'age'])


In [ ]:
print(my_dict)

{'Name': 'Abdul Hai', 'age': 25}


In [ ]:
my_dict['Company']='Contour'
print(my_dict)

{'Name': 'Abdul Hai', 'age': 25, 'Company': 'Contour'}


In [ ]:
my_dict.pop('Company')
print(my_dict)


{'Name': 'Abdul Hai', 'age': 25}


In [ ]:
print(my_dict)


{'Name': 'Abdul Hai', 'age': 25}


In [ ]:
my_dict = {'Name':'Abdul Hai' , 'age':25 , 'Company':'NRL'}

if 'Name'in my_dict:
 print(my_dict)

{'Name': 'Abdul Hai', 'age': 25, 'Company': 'NRL'}


In [ ]:
my_dict = {'Name':'Abdul Hai' , 'age':25 , 'Company':'NRL'}

if 'Name'in my_dict and 'age' in my_dict and 'Company' in my_dict:
 print(my_dict)

{'Name': 'Abdul Hai', 'age': 25, 'Company': 'NRL'}


In [ ]:
for key in my_dict:
  print(key)

Name
age
Company


In [ ]:
for Value in my_dict.values():
  print(Value)


Abdul Hai
25
NRL


In [ ]:
for key, value in my_dict.items():
    print(key, ":", value)

Name : Abdul Hai
age : 25
Company : NRL


In [ ]:
#Bitwise OR operator
# Bitwise OR (|): 101 | 011 = 111 (which is 7 in decimal)

a = 5  # (binary: 101) -> 5
b = 3  # (binary: 011) -> 3
print(a | b)  # Output: 7 (binary: 111)


7


In [ ]:
dict1 = {"a": 1, "b": 2}
dict2 = {"c": 3, "d": 4}

merged_dict = dict1 | dict2
print(merged_dict)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [ ]:
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)

merged_tuple = tuple1 + tuple2
print(merged_tuple)
#

(1, 2, 3, 4, 5, 6)


In [ ]:
dict1 = {1, 2, 3}
dict2 = {4, 5, 6}

union_dict = dict1 | dict2
print(union_dict)

{1, 2, 3, 4, 5, 6}


In [ ]:
#Array1D
#The shape (6,) means the array has 6 elements in a single dimension (1D array).
#The comma , in (6,) indicates that it's not a 2D array.
import numpy as np
arr1D = np.array ([1,2,3,4,5,6])
print(arr1D)
print("Shape:", arr1D.shape)
print(arr1D.dtype)

[1 2 3 4 5 6]
Shape: (6,)
int64


In [ ]:
#2D NumPy array (a matrix) with 2 rows and 3 columns:
arr2D = np.array([[1,2,3],[4,5,6]])
print(arr2D)
print("Shape:", arr2D.shape)
print(arr1D.dtype)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
int64


In [ ]:
#3D NumPy array (a matrix) with 3 rows and 3 columns:
arr3D = np.array([[1,2,3],[3,4,5],[6,7,8,]])
print(arr3D)
print("Shape:", arr3D.shape)
print(arr1D.dtype)

[[1 2 3]
 [3 4 5]
 [6 7 8]]
Shape: (3, 3)
int64


In [ ]:
arr_zeros = np.array(1)
print (arr_zeros)

1


In [ ]:
#Creating an array of zeros
arr_zeros = np.array((2,2))
print (arr_zeros)

[2 2]


In [ ]:
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Creating an array of ones
ones_array = np.ones((2, 4))
print(ones_array)
print (ones_array.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(2, 4)


In [ ]:
#Creating an array with a range of numbers?
arr_no = np.arange(1,10)
print(arr_no)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr_no = np.arange(1,11,2)
print(arr_no)

[1 3 5 7 9]


In [ ]:
arr_no = np.arange(10,) # 0 to 9 count
print(arr_no)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr_no = np.arange(4,) # 0 to 1 count
print(arr_no)

arr_no = np.arange(4) # Adding Comma , or not results the same
print(arr_no)

[0 1]


In [ ]:
#Use arange() when you need values with a specific step size.
#Use linspace() when you need a specific number of evenly spaced values.

arr_linspace = np.linspace(1,10)
print(arr_linspace)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Basic Function Definition & Calling

In [ ]:
def greet():
  print ('Basic Function Definition & Calling')
greet()

Basic Function Definition & Calling


In [ ]:
def add():
  a=2
  b=3
  add=a+b
  print(add)
add()

5


In [ ]:
#Return a value from a function

In [ ]:
def add(a,b):
  return a+b

result= add(2,5)
print(result)


7


In [ ]:
def no_return():
  c=10
print(no_return())

None


In [ ]:
def multiply(a,b):
 return a*b
print(multiply(4,3))

12


In [ ]:
def Div(a,b):
  return a/b
print(Div(4,2))

2.0


In [ ]:
#Use default parameter values
def greet(name = 'Guest'):
  print('Hello',name)
greet()
greet ('Abdul Hai')

Hello Guest
Hello Abdul Hai


In [ ]:
#Use keyword arguments
def describe_pet(animal_type, pet_name):
  print(f"{pet_name} is a {animal_type}")

describe_pet(animal_type ="Cow", pet_name ="Dabangg")
describe_pet(animal_type ="Goat",pet_name ="Goat")


Dabangg is a Cow
Goat is a Goat


In [ ]:
def desc_bio(name, age, gender,profession):
  print(f" My name is {name}, age is {age}, gender is {gender}, and my profession is {profession}.")

desc_bio(name = "Abdul Hai", age = "25", gender = "Male", profession = "Employee")

 My name is Abdul Hai, age is 25, gender is Male, and my profession is Employee.


In [ ]:
def greet(name, message="Hello"):
    print(f"{message}, {name}!")

greet("Alice")  # Uses default "Hello"
greet("Bob", message="Good morning")

Hello, Alice!
Good morning, Bob!


In [ ]:
def sum_all(*numbers):
    return sum(numbers)

print(sum_all(1,2,3,4))

In [ ]:
# Function Scope & Lifetime
# local scope means inside the function

def test ():
  x=10;
  print(x)
test() #local variable


10


In [ ]:
# Global scope means outside the function
x=10; #global variable
def test ():
  print(x)
test()


10


In [ ]:
#modify a global variable inside a function
x=10;
def modify():
  x=20;
  print(x)
modify()

20


In [ ]:
x=10; #global variable
def test ():
  x=20;
  print(x)
test()


20


In [ ]:
#Pandas
import pandas as pd


In [ ]:
data = {
    "customer_id" : [1,2,3,4]
}

pd.Series(data)

customer_id    [1, 2, 3, 4]
dtype: object

In [ ]:
pd.DataFrame(data)

customer_id
0            1
1            2
2            3
3            4

In [ ]:
data_1 = {
    "Customer_id" : [1,2,3],
    "Age" : [24,25,26],
    'Amount' : [100,200,300]
}

pd.DataFrame(data_1)

Customer_id  Age  Amount
0            1   24     100
1            2   25     200
2            3   26     300

In [ ]:
df = pd.DataFrame(data_1)

In [ ]:
df

Customer_id  Age  Amount
0            1   24     100
1            2   25     200
2            3   26     300

In [ ]:
#i wnt 0 1 2 s.no should named
pd.DataFrame(data_1,index=['Rafay','Mubi','hamza'])

Customer_id  Sales_Year Amount
Rafay            1        2024   100K
Mubi             2        2025   200K
hamza            3        2026   300K

In [ ]:
data_1 = {
    "Customer_id" : [1,2,3],
    "Sales_Year" : [2024,2025,2026],
    'Amount' : ['100K','200K','300K']
}

df = pd.DataFrame(data_1)



In [ ]:
df

Customer_id  Sales_Year Amount
0            1        2024   100K
1            2        2025   200K
2            3        2026   300K

In [ ]:
#Single Col means Series for e.g below
data_1 = {
    "Customer_id" : [1,2,3],
    "Sales_Year" : [2024,2025,2026],
    'Amount' : ['100K','200K','300K']
}

df = pd.DataFrame(data_1)
df ["Customer_id"]  #single col is fetched below

0    1
1    2
2    3
Name: Customer_id, dtype: int64

In [ ]:
data = pd.read_excel("/content/Customer Call List.xlsx")


In [ ]:
data

CustomerID First_Name    Last_Name  Phone_Number  \
0         1001      Frodo      Baggins  123-545-5421   
1         1002       Abed        Nadir  123/643/9775   
2         1003     Walter       /White    7066950392   
3         1004     Dwight      Schrute  123-543-2345   
4         1005        Jon         Snow  876|678|3469   
5         1006        Ron      Swanson  304-762-2467   
6         1007       Jeff       Winger           NaN   
7         1008   Sherlock       Holmes  876|678|3469   
8         1009    Gandalf          NaN           N/a   
9         1010      Peter       Parker  123-545-5421   
10        1011    Samwise       Gamgee           NaN   
11        1012      Harry    ...Potter    7066950392   
12        1013        Don       Draper  123-543-2345   
13        1014     Leslie        Knope  876|678|3469   
14        1015       Toby  Flenderson_  304-762-2467   
15        1016        Ron      Weasley  123-545-5421   
16        1017   Michael         Scott  123/643/9775   
17        1018      Clark         Kent    7066950392   
18        1019      Creed       Braton           N/a   
19        1020     Anakin    Skywalker  876|678|3469   
20        1020     Anakin    Skywalker  876|678|3469   

                                  Address Paying Customer Do_Not_Contact  \
0                   123 Shire Lane, Shire             Yes             No   
1                     93 West Main Street              No            Yes   
2                      298 Drugs Driveway               N            NaN   
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y   
4                        123 Dragons Road               Y             No   
5                        768 City Parkway             Yes            Yes   
6                       1209 South Street              No             No   
7                           98 Clue Drive               N             No   
8                        123 Middle Earth             Yes            NaN   
9              25th Main Street, New York             Yes             No   
10                  612 Shire Lane, Shire             Yes             No   
11                   2394 Hogwarts Avenue               Y            NaN   
12                       2039 Main Street             Yes              N   
13                       343 City Parkway             Yes             No   
14                          214 HR Avenue               N             No   
15                   2395 Hogwarts Avenue              No              N   
16         121 Paper Avenue, Pennsylvania             Yes             No   
17                        3498 Super Lane               Y            NaN   
18                                    N/a             N/a            Yes   
19            910 Tatooine Road, Tatooine             Yes              N   
20            910 Tatooine Road, Tatooine             Yes              N   

    Not_Useful_Column  
0                True  
1               False  
2                True  
3                True  
4                True  
5                True  
6               False  
7               False  
8               False  
9                True  
10               True  
11               True  
12              False  
13              False  
14              False  
15              False  
16              False  
17               True  
18               True  
19               True  
20               True

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# 0 to 4 entries shows
data.head()

In [ ]:
data.head(10)

CustomerID First_Name Last_Name  Phone_Number  \
0        1001      Frodo   Baggins  123-545-5421   
1        1002       Abed     Nadir  123/643/9775   
2        1003     Walter    /White    7066950392   
3        1004     Dwight   Schrute  123-543-2345   
4        1005        Jon      Snow  876|678|3469   
5        1006        Ron   Swanson  304-762-2467   
6        1007       Jeff    Winger           NaN   
7        1008   Sherlock    Holmes  876|678|3469   
8        1009    Gandalf       NaN           N/a   
9        1010      Peter    Parker  123-545-5421   

                                 Address Paying Customer Do_Not_Contact  \
0                  123 Shire Lane, Shire             Yes             No   
1                    93 West Main Street              No            Yes   
2                     298 Drugs Driveway               N            NaN   
3  980 Paper Avenue, Pennsylvania, 18503             Yes              Y   
4                       123 Dragons Road               Y             No   
5                       768 City Parkway             Yes            Yes   
6                      1209 South Street              No             No   
7                          98 Clue Drive               N             No   
8                       123 Middle Earth             Yes            NaN   
9             25th Main Street, New York             Yes             No   

   Not_Useful_Column  
0               True  
1              False  
2               True  
3               True  
4               True  
5               True  
6              False  
7              False  
8              False  
9               True

In [ ]:
#data.tail means last five entries/rows
data.tail()

CustomerID First_Name  Last_Name  Phone_Number  \
16        1017   Michael       Scott  123/643/9775   
17        1018      Clark       Kent    7066950392   
18        1019      Creed     Braton           N/a   
19        1020     Anakin  Skywalker  876|678|3469   
20        1020     Anakin  Skywalker  876|678|3469   

                           Address Paying Customer Do_Not_Contact  \
16  121 Paper Avenue, Pennsylvania             Yes             No   
17                 3498 Super Lane               Y            NaN   
18                             N/a             N/a            Yes   
19     910 Tatooine Road, Tatooine             Yes              N   
20     910 Tatooine Road, Tatooine             Yes              N   

    Not_Useful_Column  
16              False  
17               True  
18               True  
19               True  
20               True

In [ ]:
data.tail(12)

CustomerID First_Name    Last_Name  Phone_Number  \
9         1010      Peter       Parker  123-545-5421   
10        1011    Samwise       Gamgee           NaN   
11        1012      Harry    ...Potter    7066950392   
12        1013        Don       Draper  123-543-2345   
13        1014     Leslie        Knope  876|678|3469   
14        1015       Toby  Flenderson_  304-762-2467   
15        1016        Ron      Weasley  123-545-5421   
16        1017   Michael         Scott  123/643/9775   
17        1018      Clark         Kent    7066950392   
18        1019      Creed       Braton           N/a   
19        1020     Anakin    Skywalker  876|678|3469   
20        1020     Anakin    Skywalker  876|678|3469   

                           Address Paying Customer Do_Not_Contact  \
9       25th Main Street, New York             Yes             No   
10           612 Shire Lane, Shire             Yes             No   
11            2394 Hogwarts Avenue               Y            NaN   
12                2039 Main Street             Yes              N   
13                343 City Parkway             Yes             No   
14                   214 HR Avenue               N             No   
15            2395 Hogwarts Avenue              No              N   
16  121 Paper Avenue, Pennsylvania             Yes             No   
17                 3498 Super Lane               Y            NaN   
18                             N/a             N/a            Yes   
19     910 Tatooine Road, Tatooine             Yes              N   
20     910 Tatooine Road, Tatooine             Yes              N   

    Not_Useful_Column  
9                True  
10               True  
11               True  
12              False  
13              False  
14              False  
15              False  
16              False  
17               True  
18               True  
19               True  
20               True

In [ ]:
#all table info what we have uploaded
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   CustomerID         21 non-null     int64 
 1   First_Name         21 non-null     object
 2   Last_Name          20 non-null     object
 3   Phone_Number       19 non-null     object
 4   Address            21 non-null     object
 5   Paying Customer    21 non-null     object
 6   Do_Not_Contact     17 non-null     object
 7   Not_Useful_Column  21 non-null     bool  
dtypes: bool(1), int64(1), object(6)
memory usage: 1.3+ KB


In [ ]:
data.describe() #bydefault it shows the summary of numeric cols

CustomerID
count    21.000000
mean   1010.952381
std       6.127611
min    1001.000000
25%    1006.000000
50%    1011.000000
75%    1016.000000
max    1020.000000

In [ ]:
data.describe( include = 'all')

CustomerID First_Name  Last_Name  Phone_Number  \
count     21.000000         21         20            19   
unique          NaN         19         19             7   
top             NaN     Anakin  Skywalker  876|678|3469   
freq            NaN          2          2             5   
mean    1010.952381        NaN        NaN           NaN   
std        6.127611        NaN        NaN           NaN   
min     1001.000000        NaN        NaN           NaN   
25%     1006.000000        NaN        NaN           NaN   
50%     1011.000000        NaN        NaN           NaN   
75%     1016.000000        NaN        NaN           NaN   
max     1020.000000        NaN        NaN           NaN   

                            Address Paying Customer Do_Not_Contact  \
count                            21              21             17   
unique                           20               5              4   
top     910 Tatooine Road, Tatooine             Yes             No   
freq                              2              11              9   
mean                            NaN             NaN            NaN   
std                             NaN             NaN            NaN   
min                             NaN             NaN            NaN   
25%                             NaN             NaN            NaN   
50%                             NaN             NaN            NaN   
75%                             NaN             NaN            NaN   
max                             NaN             NaN            NaN   

       Not_Useful_Column  
count                 21  
unique                 2  
top                 True  
freq                  12  
mean                 NaN  
std                  NaN  
min                  NaN  
25%                  NaN  
50%                  NaN  
75%                  NaN  
max                  NaN

In [ ]:
data.describe(exclude = "int64")

First_Name  Last_Name  Phone_Number                      Address  \
count          21         20            19                           21   
unique         19         19             7                           20   
top        Anakin  Skywalker  876|678|3469  910 Tatooine Road, Tatooine   
freq            2          2             5                            2   

       Paying Customer Do_Not_Contact Not_Useful_Column  
count               21             17                21  
unique               5              4                 2  
top                Yes             No              True  
freq                11              9                12

In [ ]:
#rows and cols index ki basis pr data show krta hai.
data.iloc[0]

CustomerID                            1001
First_Name                           Frodo
Last_Name                          Baggins
Phone_Number                  123-545-5421
Address              123 Shire Lane, Shire
Paying Customer                        Yes
Do_Not_Contact                          No
Not_Useful_Column                     True
Name: 0, dtype: object

In [ ]:
data.iloc[0:3]

CustomerID First_Name Last_Name  Phone_Number                Address  \
0        1001      Frodo   Baggins  123-545-5421  123 Shire Lane, Shire   
1        1002       Abed     Nadir  123/643/9775    93 West Main Street   
2        1003     Walter    /White    7066950392     298 Drugs Driveway   

  Paying Customer Do_Not_Contact  Not_Useful_Column  
0             Yes             No               True  
1              No            Yes              False  
2               N            NaN               True

In [ ]:
data.iloc[0:3,0] # [rows,column]
                 # 0:3 rows and 0 is cols

0    1001
1    1002
2    1003
Name: CustomerID, dtype: int64

In [ ]:
df.iloc[0]

id            1
name    sufiyan
age          21
Name: 0, dtype: object

In [ ]:
df.iloc[1:] # skip 0 and rest of data will show.

id   name  age
1   2  ahmad   22
2   3    ali   23

In [ ]:
df.loc["1":,["id","age"]]



id  age
1   2   22
2   3   23

In [ ]:
data.head()

CustomerID First_Name Last_Name  Phone_Number  \
0        1001      Frodo   Baggins  123-545-5421   
1        1002       Abed     Nadir  123/643/9775   
2        1003     Walter    /White    7066950392   
3        1004     Dwight   Schrute  123-543-2345   
4        1005        Jon      Snow  876|678|3469   

                                 Address Paying Customer Do_Not_Contact  \
0                  123 Shire Lane, Shire             Yes             No   
1                    93 West Main Street              No            Yes   
2                     298 Drugs Driveway               N            NaN   
3  980 Paper Avenue, Pennsylvania, 18503             Yes              Y   
4                       123 Dragons Road               Y             No   

   Not_Useful_Column  
0               True  
1              False  
2               True  
3               True  
4               True

In [ ]:
# **loc vs iloc**
# loc: label based (column names)
# iloce: Index based

# loc: last value is included
# iloc: last value is excluded

In [ ]:
data.column()

AttributeError: 'DataFrame' object has no attribute 'column'

In [ ]:
#Pattern Questions
n=5
for i in range (1,n+1):
  print('.' * i)

.
..
...
....
.....


In [ ]:
n=5
for i in range (1,n+3): #n+3 decides the addition rows
  print('*' * i)

*
**
***
****
*****
******
*******


In [ ]:
n=5
for i in range (4,n+1):#4 mean starting row like **** and #n=3 decides the addition rows
  print('*' * i)

****
*****


In [ ]:
# Inverted Right-Angled Triangle



n=5
for i in range (n,0,-1): #
  print('*' * i)


# E X P L A N A T I O N:
# The range(n, 0, -1) function is used to generate numbers in a decreasing order. Let's break it down:
# range(start, stop, step)
# start = n → The loop starts at n (in this case, 5).
# stop = 0 → The loop runs until 0, but 0 is not included.
# step = -1 → The loop decreases by 1 in each iteration.

*****
****
***
**
*


In [ ]:
#Leading Spaces: " " * (n - i)

# This creates indentation to center the stars.
# The number of spaces decreases as i increases.
# Formula: (n - i)
# Example for n = 5:
# i = 1: 5 - 1 = 4 spaces
# i = 2: 5 - 2 = 3 spaces
# i = 3: 5 - 3 = 2 spaces
# i = 4: 5 - 4 = 1 space
# i = 5: 5 - 5 = 0 spaces
# Asterisk (*) Pattern: "*" * (2*i - 1)

# This determines the number of * printed in each row.
# Formula: (2*i - 1), which ensures the count follows the pattern of odd numbers.
# Example for n = 5:
# i = 1: (2*1 - 1) = 1 star
# i = 2: (2*2 - 1) = 3 stars
# i = 3: (2*3 - 1) = 5 stars
# i = 4: (2*4 - 1) = 7 stars
# i = 5: (2*5 - 1) = 9 stars


# PYRAMID Pattern
n=10
for i in range (1, n+1):
  print(" " * (n-i) + '|' * (2*i-1))


         |
        |||
       |||||
      |||||||
     |||||||||
    |||||||||||
   |||||||||||||
  |||||||||||||||
 |||||||||||||||||
|||||||||||||||||||


In [ ]:
# Inverted Pyramid
n=10
for i in range (n,0,-1):
  print(" " * (n-i) + '|' * (2*i-1))

|||||||||||||||||||
 |||||||||||||||||
  |||||||||||||||
   |||||||||||||
    |||||||||||
     |||||||||
      |||||||
       |||||
        |||
         |


In [ ]:
# Diamond Pattern
n=5
for i in range (1,n+1):
  print(" " * (n-i) + "." * (2*i-1))

for i in range (n-1,0,-1):
    print(" " * (n-i) + "." * (2*i-1))

    .
   ...
  .....
 .......
.........
 .......
  .....
   ...
    .


In [ ]:
n=5
for i in range (1,n+1):
  print(" " * (n-i) + "1" * (2*i-1))

for i in range (n-1,0,-1):
    print(" " * (n-i) + "1" * (2*i-1))

    1
   111
  11111
 1111111
111111111
 1111111
  11111
   111
    1


In [ ]:
#Number Triangle
n=5
for i in range (1,n+1):
  print(" ".join(str (j) for j in range (1,i+1)))

1
1 2
1 2 3
1 2 3 4
1 2 3 4 5


In [ ]:
#Number Inverted Triangle
n=8
for i in range (n,0,-1): #inverted
  print(" " .join(str (j) for j in range (1,i+1)))

1 2 3 4 5 6 7 8
1 2 3 4 5 6 7
1 2 3 4 5 6
1 2 3 4 5
1 2 3 4
1 2 3
1 2
1


In [ ]:
n=8
for i in range (n,0,-1): #inverted

  print(' '.join(map(str, range(1, i+1))))

1 2 3 4 5 6 7 8
1 2 3 4 5 6 7
1 2 3 4 5 6
1 2 3 4 5
1 2 3 4
1 2 3
1 2
1


In [ ]:
#Alphabet Pyramid
n=5
for i in range (1,n+1):
  print(" " * (n-i) + chr(64+i) * (2*i-1))

    A
   BBB
  CCCCC
 DDDDDDD
EEEEEEEEE


In [ ]:
n=5
for i in range (1,n+1):
  print(" " * (n-i) + " ".join(chr (65+x) for x in range(i)))

    A
   A B
  A B C
 A B C D
A B C D E


In [ ]:
# 🤯 𝐃𝐢𝐝 𝐲𝐨𝐮 𝐤𝐧𝐨𝐰 𝐭𝐡𝐢𝐬?
# a = 7
# b = 7
# print(a is b) # True ✅
# print(a == b) # True ✅

# a = 258
# b = 258
# print(a is b) # False ❌
# print(a == b) # True ✅

# Wait… why is a is b False for 257 but a == b is still True? 🤔

# 🔍 Understanding is vs == in Python
# ✔️ is → checks if two variables point to the same memory location (identity check).
# ✔️ == → checks if two variables hold the same value (equality check).
# 🧪 The Python Integer Caching Trick
# Python caches integers from -5 to 256 for optimization. Since these numbers are used frequently, Python reuses the same memory address.
# However, numbers outside this range (like 257) are stored separately, so a is b returns False, even though a == b remains True.

In [ ]:
a = 7
b = 7
print(a is b)

True


In [ ]:
a = 256
b = 256
print(a is b)

True


In [ ]:
#int values from -5 to 256 remain
a = 257
b = 257
print(a is b)

False


In [ ]:
# Lambda Functions
# Q-) why we use it?
# Ans-) Lambda functions in Python are anonymous, single-expression functions used for short,
# simple operations without defining full functions using def.

# Here’s why we use them:


In [ ]:
#Without lambda
def square(x):
    return x ** 2

print(square(5))

#With lambda
square = lambda x: x ** 2
print(square(5))

25
25


In [ ]:
add = lambda a,b:a+b
print(add(4,5))

9


In [ ]:
subt = lambda a,b:a-b
print(subt(4,5))

-1


In [ ]:
even = lambda x: 'Even' if x % 2== 0 else 'odd'
print(even(5))

odd


In [ ]:
max_num = lambda a,b: a if a>b else b
print(max_num(29,31))

31


In [ ]:
Coding = lambda x:len(x)
print(Coding("Programming"))

11


In [ ]:
nums = [2,4,6,8]
doubled = list(map(lambda c: c*2,nums))
print(doubled)

[4, 8, 12, 16]


In [ ]:
# https://chatgpt.com/c/67ce6301-c4a4-800b-ad98-396502c771b7
#                    ASSIGNMENT QUESTION

# Topics
# 1-) Taking from user Input Questions
# 2-) String Questions
# 3-) List
# 4-) Dictionaries

Taking Input from User:

1.Write a Python program that takes a user's name and age as input and prints a message saying, “Hello [name], you are [age] years old.”

2.Write a program that asks the user for two numbers, adds them, and prints the result.

3.Create a program that asks the user for a temperature in Celsius and converts it to Fahrenheit.

4.Ask the user for their birth year and calculate their age.

5.Write a program that takes three numbers from the user and prints their average.


In [ ]:
#1.Write a Python program that takes a user's name and age as input and prints a message saying, “Hello [name], you are [age] years old.”

# user = str(input('Enter ur name: '))
name = input ('Enter your Name: ')
age = input ('Enter your Age: ')

print(f"Hello {name} , you are {age} years old." )

Enter your Name: Hai
Enter your Age: 25
Hello Hai , you are 25 years old.


In [ ]:
#2.Write a program that asks the user for two numbers, adds them, and prints the result.

a=int(input("Enter First No: "))
b=int(input("Enter Second No: "))

print(f"Sum of two number is: {a+b}.")


Enter First No: 2
Enter Second No: 3
Sum of two number is: 5.


In [ ]:
Celsius = float(input("Tempratue is: "))
fahrenheit  = (Celsius * 9/5) +32

print(f"{Celsius} C Temprature in fahrenheit : {fahrenheit }")

Tempratue is: 37
37.0 C Temprature in fahrenheit : 98.6


In [ ]:
3.Create a program that asks the user for a temperature in Celsius and converts it to Fahrenheit.

#To convert a temperature from Fahrenheit to Celsius, use the formula:

fahrenheit = float (input('Temp is: '))
celsius = (fahrenheit - 32)* 5/9

print(f"{fahrenheit} temp in celsius: {celsius}")


Temp is: 100
100.0 temp in celsius: 37.77777777777778


In [ ]:
#4.Ask the user for their birth year and calculate their age
from datetime import datetime

Birth_Year = int(input('Your Birth Year: '))

Current_Year = datetime.now().year
Age = Current_Year - Birth_Year

print(f'Your Age is: {Age}')






Your Birth Year: 1999
Your Age is: 26


In [ ]:
#For multiple print use Loop
from datetime import datetime

Current_Year = datetime.now().year


for i in range(5):
  Birth_Year = int(input('Your Birth Year: '))
  Age = Current_Year - Birth_Year
  print(f'Your age is, {Age}')

Your Birth Year: 1999
Your age is, 26
Your Birth Year: 2005
Your age is, 20
Your Birth Year: 1975
Your age is, 50
Your Birth Year: 1983
Your age is, 42
Your Birth Year: 1800
Your age is, 225


In [ ]:
#5.Write a program that takes three numbers from the user and prints their average.

Number = int(input('Enter Number: '))
average = Number/3
print(f"Average of three number is: {average}")

Enter Number: 12
Average of three number is: 4.0


2) String Questions

1.Write a Python program that takes a string input from the user and prints it in reverse order.

2.Ask the user for a sentence and count the number of vowels in it.

3.Write a program that replaces all spaces in a user-given string with underscores (_).

4.Take a string from the user and check if it is a palindrome.

5.Write a program to capitalize the first letter of each word in a given string. **bold text**




In [5]:
#Q1-)
reverse = input("Enter String:")
print(reverse [::-1])

Enter String:iah ludba
abdul hai


In [13]:
def count_vowels(sentence):
    vowels = "aeiouAEIOU"
    count = sum(1 for char in sentence if char in vowels)
    return count
sentence = "Abdul Hai is a hardworking developer"
vowel_count = count_vowels(sentence)
print(f"The number of vowels in the sentence is: {vowel_count}")

The number of vowels in the sentence is: 13


In [14]:
sentence = input("Enter a sentence: ")
count = 0
i = 0

while i < len(sentence):
    if sentence[i] in "aeiouAEIOU":
        count += 1
    i += 1  # Move to next character

print("Number of vowels:", count)

Enter a sentence: MY NAME IS ABDUL HAI
Number of vowels: 7


In [15]:
#Q3-)
Replace = input("Enter String: ")
print(Replace.replace(" ","_"))

Enter String: MY NAME IS ABDUL HAI
MY_NAME_IS_ABDUL_HAI


In [16]:
Words = input("Enter String: ")
print(Words.replace(" ","_"))

Enter String: MY NAME IS ABDUL HAI
MY_NAME_IS_ABDUL_HAI


In [22]:
#Q4-)Main Condition/Logic [::-1] and adding .lower() means it will handle the case sensitivity
Palindrome = input("Enter String: ")
if Palindrome.lower() == Palindrome.lower()[::-1]:
  print("Palindrome")
else:
  print("Not Palindrome")


Enter String: Mom
Palindrome


In [23]:
# Q5-) Main logic is i used .title()
Capitalize = input("Enter String: ")
print(Capitalize.title())

Enter String: Abdul Hai is a hardworking developer
Abdul Hai Is A Hardworking Developer


In [26]:
# Q-) 5.1.Write a program to capitalize the whole sentence in a given string. bold text
#.upper() is the logic
Capitalize = input("Enter String: ")
print(Capitalize.upper())

Enter String: i m a bad person
I M A BAD PERSON


In [27]:
# Get input from the user
sentence = input("Enter a sentence: ")

# Convert the sentence to uppercase
capitalized_sentence = sentence.upper()

# Print the result
print("Capitalized Sentence:", capitalized_sentence)

Enter a sentence: i m a good boy
Capitalized Sentence: I M A GOOD BOY


3) List Questions

1.Ask the user to enter five numbers, store them in a list, and print the sum of the numbers.

2.Write a program that takes a list of numbers from the user and finds the maximum and minimum numbers.

3.Ask the user to enter a list of names, sort them alphabetically, and display the sorted list.

4.Write a program that removes duplicates from a user-given list.

5.Create a program that takes two lists from the user and merges them into one without duplicates. **bold text**

4) Dictionary Questions

1.Write a program that asks the user for three key-value pairs and stores them in a dictionary, then prints the dictionary.

2.Take a dictionary of student names as keys and their marks as values, then print the name of the student with the highest marks.

3.Ask the user to enter a sentence and count the frequency of each word, storing the result in a dictionary.

4.Create a dictionary with country names as keys and their capitals as values. Allow the user to enter a country and display its capital.

5.Write a program that takes a dictionary from the user and allows them to search for a key. If the key exists, print its value; otherwise, display a message saying the key is not found. **bold text**
